ENTER_NAME_TEXT = "Napíš !ais [priezvisko meno] (nie opačne), napriklad : !ais Mrkvicka Jozko. Ja overím že či si z STU!"
AIS_CONFIRMED = "Podarilo sa mi ťa nájsť v zozname ludí na STU, môžeš pokračovať!"
AIS_DENIED = "Nenašiel som nikoho s menom \"{}\" na STU!, skús znova zadať meno do !ais príkazu."
PERMISSION_DENIED = "Nemáš povolenie používať prikaz \"{}\" !"
NOT_FOUND = "NOT FOUND"
NOT_FOUND_MSG_LOL = "Nenašiel som hráča \"{}\" na servery \"{}\", skús znova zadať správne meno."
ROLE_NOT_FOUND = "Rola \"{}\" neexistuje, pre League of Legends poznám len role : ADC, MID, TOP, SUPP, JUNGLE."
